-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 11:48:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cartes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cartes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cartes` DEFAULT CHARACTER SET utf8mb4 ;
USE `cartes` ;

-- -----------------------------------------------------
-- Table `cartes`.`t_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartes`.`t_roles` (
  `id_roles` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rollibelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartes`.`t_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartes`.`t_users` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usenom` VARCHAR(128) NOT NULL,
  `useprenom` VARCHAR(128) NOT NULL,
  `usemail` VARCHAR(255) NOT NULL,
  `usepwd` VARCHAR(255) NOT NULL,
  `useactif` INT NOT NULL DEFAULT 0,
  `usedatetime` DATETIME NOT NULL,
  `usetoken` CHAR(64) NOT NULL,
  `id_roles` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_t_users_t_roles_idx` (`id_roles` ASC),
  CONSTRAINT `fk_t_users_t_roles`
    FOREIGN KEY (`id_roles`)
    REFERENCES `cartes`.`t_roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartes`.`t_parties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartes`.`t_parties` (
  `t_users_id_user` INT UNSIGNED NOT NULL,
  `t_users_id_user1` INT UNSIGNED NOT NULL,
  `partiedebut` DATETIME NOT NULL,
  `partiefin` DATETIME NULL,
  `partienbrtours` INT NOT NULL DEFAULT 0,
  `score` VARCHAR(10) NULL,
  PRIMARY KEY (`t_users_id_user`, `t_users_id_user1`),
  INDEX `fk_t_users_has_t_users_t_users2_idx` (`t_users_id_user1` ASC),
  INDEX `fk_t_users_has_t_users_t_users1_idx` (`t_users_id_user` ASC),
  CONSTRAINT `fk_t_users_has_t_users_t_users1`
    FOREIGN KEY (`t_users_id_user`)
    REFERENCES `cartes`.`t_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_users_has_t_users_t_users2`
    FOREIGN KEY (`t_users_id_user1`)
    REFERENCES `cartes`.`t_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cartes`.`t_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cartes`.`t_news` (
  `id_new` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `chapo` TEXT NOT NULL,
  `contenu` TEXT NOT NULL,
  `t_users_id_user` INT UNSIGNED NOT NULL,
  `dateredaction` DATETIME NULL,
  `datepublication` DATETIME NULL,
  PRIMARY KEY (`id_new`, `t_users_id_user`),
  INDEX `fk_t_news_t_users1_idx` (`t_users_id_user` ASC),
  CONSTRAINT `fk_t_news_t_users1`
    FOREIGN KEY (`t_users_id_user`)
    REFERENCES `cartes`.`t_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
